# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fcab3ec9db1344aacf53c33754ff23380a25dc6036a902b17340d2d125ceb0851691366f01b663957bfa9f7b116f1fd5ebdd8fd6b3335cf361e2f2e42f716f0

test:
  secret_key_base: 48fcef69b6853c0f9277de78237deb7c9d8830a68a4ff6e1e224bcc93814a35b48e1a3e70b1dffb6492428b31ee4ae7032ced769ef434f0b71155ac0e670dca4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
